version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/fridge_app
    steps:
      - checkout:
          path: ~/fridge_app
      - ruby/install-deps

  test:
      docker:
        - image: circleci/ruby:2.6.5
        - image: circleci/mysql:5.5
          environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: fridge_app_test
      environment:
        BUNDLE_JOBS: "3"
        BUNDLE_RETRY: "3"
        FRIDGE_APP_DATABASE_HOST: "127.0.0.1"
        RAILS_ENV: test
      working_directory: ~/fridge_app
      steps:
        - checkout:
            path: ~/fridge_app
        - ruby/install-deps
        - run:
            name: Database setup
            command: bundle exec rails db:migrate
        - run:
            name: install dependencies
            command: yarn install --check-files
        - run:
            name: test
            command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build