version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
    working_directory: ~/fridge_app
    steps:
      - checkout:
          path: ~/fridge_app
      - ruby/install-deps
      - run:
            name: yarn Install
            command: yarn install

  test:
      docker:
        - image: circleci/ruby:2.6.5-node
        - image: circleci/mysql:5.5
          environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: fridge_app_test
      environment:
        BUNDLE_JOBS: "3"
        BUNDLE_RETRY: "3"
        FRIDGE_APP_DATABASE_HOST: "127.0.0.1"
        RAILS_ENV: test
      working_directory: ~/fridge_app
      steps:
        - checkout:
            path: ~/fridge_app
        - ruby/install-deps
        - run:
            name: yarn Install
            command: yarn install
        - run:
            name: Database setup
            command: bundle exec rails db:migrate
        - run:
            name: test
            command: bundle exec rspec
  deploy:
        docker:
          - image: circleci/ruby:2.6.5-node
        steps:
          - checkout
          - setup_remote_docker:
              version: 19.03.13
          - heroku/install
          - run:
              name: heroku login
              command: heroku container:login
          - run:
              name: push docker image
              command: heroku container:push web -a $HEROKU_APP_NAME
          - run:
              name: release docker image
              command: heroku container:release web -a $HEROKU_APP_NAME
          - run:
              name: datebase setup
              command: heroku run bundle exec rails db:migrate

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master